feat: Add L02-07
nitrofimenko/Homework-solution pull request #12
Opened 2022-07-15 14:38 UTC by nitrofimenko

Плохо получилось.
Смешал в классе поля и свойства. Поля для внутреннего употребления, свойства public.
Пришлось дублировать массив positions. Не придумал, как этого избежать.

Создать класс Employee.
В теле класса создать пользовательский конструктор, который принимает два строковых аргумента, и
инициализирует поля, соответствующие фамилии и имени сотрудника.
Создать метод рассчитывающий оклад сотрудника (в зависимости от должности и стажа) и налоговый
сбор.
Написать программу,
1 дает на выбор два действия создать сотрудника, вывести информацию по сотрудникам компании
2 Действие создать сотрудника запрашивает ввод информации о сотруднике: ФИО, должность, стаж
3 вывести информацию по сотрудникам компании выводит на экран информацию о сотруднике (фамилия, имя, должность), оклад и налоговый сбор.

2022-07-19 13:19 UTC, MTrofimenko commented on src/L01/Properties/launchSettings.json
> +{
а зачем этот файл нужен?

2022-07-19 13:19 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +        public void CountSalaryAndTax()
Давай немного переделаем подход. 
Каждый раз когда меняется должность или опыт должны пересчитываться оклад и налог автоматически. 
Я предлагаю сделать два метода: SetPosition() & SetExperience(), в каждом из которых мы присваиваем новое значение и смотрим, если оба поля (Position & Experience) не null - то пересчитать salary и tax.

2022-07-19 13:19 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +            string[] positions = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };
Лучше этот масив сделать константой в отдельном классе, чтобы и класс Employee и класс EmployeeFactory могли на нее ссылаться

2022-07-23 11:03 UTC, nitrofimenko commented on src/L01/Properties/launchSettings.json
> +{
Я в файлы не заглядываю. Даже не представляю, какие из них нужны, откуда они берутся и чем занимаются.

2022-07-23 11:16 UTC, nitrofimenko commented on src/L02-07/Employee.cs
> +            string[] positions = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };
const string[] POSITIONS = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };
Не получается. Как сделать константу?

2022-07-25 08:56 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +            string[] positions = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };
public static readonly string[] Aa = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };

2022-08-04 07:52 UTC, MTrofimenko commented on src/L01/Properties/launchSettings.json
> +{
Стоит заглядывать, чтобы проверять, что ты отправляешь людям читать.
Это файл прокта L01

2022-08-04 07:55 UTC, MTrofimenko commented on src/L02-07/Common.cs
> +        public static readonly string[] positions = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };
Имена публичных полей пишутся с большой буквы.

2022-08-04 07:55 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +            if (Position != null && Experience!=null)
Вторая часть проверки избыточна. Мы же только что присвоили Experience значению double, как он может біть null?

2022-08-04 15:15 UTC, nitrofimenko commented on src/L02-07/Common.cs
> +        public static readonly string[] positions = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };
Любых public или только public static?

2022-08-04 16:07 UTC, nitrofimenko commented on src/L02-07/Employee.cs
> +            if (Position != null && Experience!=null)
Проверку на меньше нуля делать?
В SetPosition нужна проверка Experience на null и на отрицательность?

2022-08-05 13:03 UTC, MTrofimenko commented on src/L02-07/Common.cs
> +        public static readonly string[] positions = { "Junior", "Middle", "Senior", "TeamLead", "Architect" };
Любых публичных

2022-08-05 13:04 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +            if (Position != null && Experience!=null)
В SetExperience добавить проверку на меньше нуля и не присваивать, если меньше.
SetPosition добавить проверку на null

2022-08-09 11:36 UTC, MTrofimenko requested changes

2022-08-09 11:36 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +            Experience = experience;
должно быть так
```
if(experience < 0) {
   Console.WriteLine("Experience can't be less that 0.")
   return;
}
Experience = experience;
if (Position != null)
{
   CountSalaryAndTax();
}
```

2022-08-09 11:36 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +            if (positionNumber >= 0)
```
var length = Common.Positions.Length;
if(positionNumber > length - 1 || positionNumber < 0) {
  Console.WriteLine("positionNumber  is out of scope of available values");
  return;
}
 Position = Common.Positions[positionNumber];
CountSalaryAndTax();   
```

2022-08-09 12:33 UTC, nitrofimenko commented on src/L02-07/Employee.cs
> +            if (positionNumber >= 0)
var length = Common.Positions.Length;
Ради однократного использования?

2022-08-15 15:08 UTC, MTrofimenko commented on src/L02-07/Employee.cs
> +            if (positionNumber >= 0)
yes

2022-08-15 15:09 UTC, MTrofimenko approved these changes

2022-08-15 15:10 UTC, merged